/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package model;

// import org.junit.Test;
//import static org.junit.Assert.*;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;
import model.Calculadora;

import java.util.ArrayList;

public class CalculadoraTest {
    @Test public void testParse() {
        Calculadora classUnderTest = new Calculadora();
        
        ArrayList<String> compara = new ArrayList<String>();
        
        //headlines atuais
        compara.add("COVID-19 pandemic");
        compara.add("White stork");
        compara.add("Iranian support vessel Konarak");
        compara.add("Visakhapatnam gas leak");
        compara.add("Deaths in 2020");
        compara.add("Portal:Current events");
        compara.add("Deaths in 2020");
        compara.add("Wikipedia:In the news/Candidates");
        
        //console - exibe headline atual
        System.out.println(classUnderTest.parseFromWiki());
        
        ArrayList<String> results =classUnderTest.parseFromWiki();
        assertEquals(compara.get(0), results.get(0));
    }
}




// import static org.junit.jupiter.api.Assertions.assertEquals;
// import org.junit.jupiter.api.Test;
// import model.Calculadora;

// public class CalculadoraTest {
// 	@Test
// 	public void somarTest() {
// 		Calculadora calc = new Calculadora();
// 		int resultado = calc.somar(3,4);
// 		assertEquals(7, resultado);
// 	}
// }